ORIGINAL_BANKING77_INTENT_MAPPING = {
    0:	"activate_my_card",
1:	"age_limit",
2:	"apple_pay_or_google_pay",
3:	"atm_support",
4:	"automatic_top_up",
5:	"balance_not_updated_after_bank_transfer",
6:	"balance_not_updated_after_cheque_or_cash_deposit",
7:	"beneficiary_not_allowed",
8:	"cancel_transfer",
9:	"card_about_to_expire",
10:	"card_acceptance",
11:	"card_arrival",
12:	"card_delivery_estimate",
13:	"card_linking",
14:	"card_not_working",
15:	"card_payment_fee_charged",
16:	"card_payment_not_recognised",
17:	"card_payment_wrong_exchange_rate",
18:	"card_swallowed",
19:	"cash_withdrawal_charge",
20:	"cash_withdrawal_not_recognised",
21:	"change_pin",
22:	"compromised_card",
23:	"contactless_not_working",
24:	"country_support",
25:	"declined_card_payment",
26:	"declined_cash_withdrawal",
27:	"declined_transfer",
28:	"direct_debit_payment_not_recognised",
29:	"disposable_card_limits",
30:	"edit_personal_details",
31:	"exchange_charge",
32:	"exchange_rate",
33:	"exchange_via_app",
34:	"extra_charge_on_statement",
35:	"failed_transfer",
36:	"fiat_currency_support",
37:	"get_disposable_virtual_card",
38:	"get_physical_card",
39:	"getting_spare_card",
40:	"getting_virtual_card",
41:	"lost_or_stolen_card",
42:	"lost_or_stolen_phone",
43:	"order_physical_card",
44:	"passcode_forgotten",
45:	"pending_card_payment",
46:	"pending_cash_withdrawal",
47:	"pending_top_up",
48:	"pending_transfer",
49:	"pin_blocked",
50:	"receiving_money",
51:	"Refund_not_showing_up",
52:	"request_refund",
53:	"reverted_card_payment",
54:	"supported_cards_and_currencies",
55:	"terminate_account",
56:	"top_up_by_bank_transfer_charge",
57:	"top_up_by_card_charge",
58:	"top_up_by_cash_or_cheque",
59:	"top_up_failed",
60:	"top_up_limits",
61:	"top_up_reverted",
62:	"topping_up_by_card",
63:	"transaction_charged_twice",
64:	"transfer_fee_charged",
65:	"transfer_into_account",
66:	"transfer_not_received_by_recipient",
67:	"transfer_timing",
68:	"unable_to_verify_identity",
69:	"verify_my_identity",
70:	"verify_source_of_funds",
71:	"verify_top_up",
72:	"virtual_card_not_working",
73:	"visa_or_mastercard",
74:	"why_verify_identity",
75:	"wrong_amount_of_cash_received",
76:	"wrong_exchange_rate_for_cash_withdrawal",
}

BANKING77_INTENT_MAPPING = {
    0:	"Activate My Card",
    1:	"Children family account questions", # Age limit
    2:	"Apple Pay or Google Pay",
    3:	"ATM Support",
    4:	"Automatic Top Up",
    5:	"Balance Not Updated After Bank Transfer",
    6:	"Balance Not Updated After Cheque or Cash Deposit",
    7:	"Beneficiary Not Allowed Can't Transfer",
    8:	"Cancel Transfer",
    9:	"Card About to Expire",
    10:	"Card Acceptance",
    11:	"When Card Arrives",
    12:	"Card Delivery Shipping Estimate",
    13:	"Card Linking",
    14:	"Card Not Working",
    15:	"Card Payment Fee Charged",
    16:	"Card Payment Not Recognized",
    17:	"Exchange Rate Payment Issues",
    18:	"Card Swallowed",
    19:	"Cash Withdrawal Charge",
    20:	"Cash Withdrawal Not Recognized",
    21:	"Change PIN",
    22:	"Freeze Account Stolen Card Using Account",
    23:	"Contactless Not Working",
    24:	"Country Support",
    25:	"Declined Card Payment",
    26:	"Declined Cash Withdrawal",
    27:	"Declined Transfer",
    28:	"Direct Debit Payment Not Recognized",
    29:	"Disposable Card Limits",
    30:	"Edit Personal Details",
    31:	"Exchange Charge",
    32:	"Exchange Rate",
    33:	"Exchange via App",
    34:	"Extra Charge on Statement",
    35:	"Failed Transfer",
    36:	"Fiat Currency Support",
    37:	"Get Disposable Virtual Card",
    38:	"What Where Pin",
    39:	"Getting Spare Card",
    40:	"Getting Virtual Card",
    41:	"Lost or Stolen Card",
    42:	"Lost or Stolen Phone",
    43:	"Order Physical Card",
    44:	"Passcode Forgotten",
    45:	"Pending Card Payment",
    46:	"Pending Cash Withdrawal",
    47:	"Pending Top Up",
    48:	"Pending Transfer",
    49:	"PIN Blocked",
    50:	"Receiving Money",
    51:	"Refund Not Showing Up",
    52:	"Request Refund",
    53:	"Reverted Card Payment",
    54:	"Supported Cards and Currencies",
    55:	"Terminate Account",
    56:	"Swift Transfer",
    57:	"Top Up by Card Charge",
    58:	"Top Up by Cash or Cheque",
    59:	"Top Up Failed",
    60:	"Top Up Limits",
    61:	"Top Up Reverted",
    62:	"Transferring to card",
    63:	"Transaction Charged Twice",
    64:	"Transfer Fee Charged",
    65:	"Transfer money into Account specific questions",
    66:	"Transfer Not Received by Recipient",
    67:	"When transfer will available",
    68:	"Unable to Verify Identity",
    69:	"Verify My Identity",
    70:	"Verify Source of Funds",
    71:	"Verify Top Up",
    72:	"Virtual Card Not Working",
    73:	"Visa or Mastercard",
    74:	"Why Verify Identity",
    75:	"Wrong Amount of Cash Received",
    76:	"Wrong Exchange Rate for Cash Withdrawal",
}


FEW_SHOT_EXAMPLES = {
    22:	["Freeze Account", "Stolen", "Somebody Using My Account Or Card Or Information", "Fraud Hack", "Improper Use"]
}


L2_MAPPING = {
    "Card Issues": [
        "Activate My Card",
        "Card About to Expire",
        "Card Acceptance",
        "Card Arrival and Card Location",
        "Card Delivery Estimate",
        "Card Linking",
        "Card Not Working",
        "Card Payment Fee Charged",
        "Card Payment Not Recognized",
        "Card Payment Wrong Exchange Rate",
        "Card Swallowed",
        "Compromised Card",
        "Contactless Not Working",
        "Declined Card Payment",
        "Lost or Stolen Card",
        "Order Physical Card",
        "Pending Card Payment",
        "Reverted Card Payment",
        "Virtual Card Not Working",
        "Visa or Mastercard"
    ],
    "Payment Issues": [
        "Declined Cash Withdrawal",
        "Declined Transfer",
        "Direct Debit Payment Not Recognized",
        "Failed Transfer",
        "Pending Cash Withdrawal",
        "Pending Transfer",
        "Transaction Charged Twice",
        "Transfer Fee Charged",
        "Transfer into Account",
        "Transfer Not Received by Recipient",
        "Transfer Timing"
    ],
    "Top Up Issues": [
        "Automatic Top Up",
        "Balance Not Updated After Bank Transfer",
        "Balance Not Updated After Cheque or Cash Deposit",
        "Pending Top Up",
        "Top Up by Bank Transfer Charge",
        "Top Up by Card Charge",
        "Top Up by Cash or Cheque",
        "Top Up Failed",
        "Top Up Limits",
        "Top Up Reverted",
        "Topping Up by Card",
        "Verify Top Up"
    ],
    "Identity Verification Issues": [
        "Unable to Verify Identity",
        "Verify My Identity",
        "Verify Source of Funds",
        "Why Verify Identity"
    ],
    "Refund and Charge Issues": [
        "Extra Charge on Statement",
        "Refund Not Showing Up",
        "Request Refund"
    ],
    "ATM and Cash Withdrawal Issues": [
        "ATM Support",
        "Cash Withdrawal Charge",
        "Cash Withdrawal Not Recognized",
        "Wrong Amount of Cash Received",
        "Wrong Exchange Rate for Cash Withdrawal"
    ],
    "Exchange Issues": [
        "Exchange Charge",
        "Exchange Rate",
        "Exchange via App"
    ],
    "Card Security Issues": [
        "Compromised Card",
        "Passcode Forgotten",
        "PIN Blocked"
    ],
    "Card Replacement Issues": [
        "Getting Spare Card",
        "Getting Virtual Card",
        "Get Disposable Virtual Card",
        "Get Physical Card"
    ],
    "Country and Currency Support Issues": [
        "Country Support",
        "Fiat Currency Support",
        "Supported Cards and Currencies"
    ],
    "General Account Issues": [
        "Terminate Account",
        "Edit Personal Details"
    ],
    "Technical and Support Issues": [
        "Apple Pay or Google Pay",
        "Beneficiary Not Allowed"
    ],
    "Device and Access Issues": [
        "Lost or Stolen Phone",
        "Passcode Forgotten"
    ],
    "PIN and Passcode Issues": [
        "Change PIN",
        "PIN Blocked",
        "Passcode Forgotten"
    ],
    "Age Limit Or Beneficiary": [
        "Age Limit",
        "Beneficiary Not Allowed"
    ]
}
