ATIS_INTENT_MAPPING = {
    'abbreviation': "Abbreviation and Fare Code Meaning Inquiry",
    'aircraft': "Aircraft Type Inquiry",
    # 'aircraft+flight+flight_no': "Flight Details Inquiry",
    'airfare': "Airfare Information Requests",
    # 'airfare+flight_time': "Flight Cost and Duration Inquiry",
    'airline': "Airline Information Request",
    # 'airline+flight_no': "Airline and Flight Number Query",
    'airport': "Airport Information and Queries",
    'capacity': "Aircraft Seating Capacity Inquiry",
    'cheapest': "Cheapest Fare Inquiry",
    'city': "Airport Location Inquiry",
    'distance': "Airport Distance Inquiry",
    'flight': "Flight Booking Request",
    # 'flight+airfare': "Flight and Fare Inquiry",
    'flight_no': "Flight Number Inquiry",
    'flight_time': "Flight Schedule Inquiry",
    'ground_fare': "Ground Transportation Cost Inquiry",
    'ground_service': "Ground Transportation Inquiry",
    'ground_service+ground_fare': "Airport Ground Transportation and Cost Query",
    'meal': "Inquiry about In-flight Meals",
    'quantity': "Flight Quantity Inquiry",
    'restriction': "Flight Restriction Inquiry"
}